#!/bin/bash

function handle {
  if [[ ${1:0:13} == "windowtitlev2" ]]; then
    # Remove the "windowtitlev2>>" prefix
    event_data="${1#windowtitlev2>>}"
    # Split into address and title using comma as delimiter
    IFS=',' read -r win_address title <<< "$event_data"
    # Construct the window identifier
    window=address:0x$win_address
    echo $window
    echo $title
    printf "\n"
    if [[ $title =~ "3D Viewport" ]]; then

      hyprctl dispatch movetoworkspace 6, $window
      hyprctl dispatch fullscreen
      hyprctl dispatch focusmonitor DP-1
      hyprctl focuswindow class:blender
      hyprctl dispatch fullscreen
    fi
  fi
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
