#!/bin/bash

monitorId=1
monitorInfo=$(hyprctl monitors | awk '/^Monitor [^ ]+ \(ID '$monitorId'\):/,/^$/' )
echo $monitorInfo


# Use awk to extract the "transform" parameter and remove any non-numeric characters
transform=$(echo "$monitorInfo" | awk -F 'transform:' '{print $2}' | tr -cd '[:digit:]')

# Print the extracted "transform" parameter
echo $transform


if [ $transform -eq 0 ]
then
  hyprctl --batch "
  keyword monitorv2[DP-2]:position 2560x150;
  keyword monitorv2[DP-2]:transform 1"
else
  hyprctl --batch "
  hyprctl keyword monitorv2[DP-2]:position 2560x550;
  keyword monitorv2[DP-2]:transform 0"
fi
