# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄
source=~/.config/hypr/execs.conf


# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀ 
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█
$monitor_01 = DP-1
$monitor_02 = DP-2
$monitor_03 = HDMI-A-1


monitorv2 {
  output = $monitor_01
  mode =  2560x1440@144
  # mode =  1920x1080@144
  position = 0x0
  scale = 1
  transform = 0
}

monitorv2 {
  output = $monitor_02
  mode =  1920x1080@60
  position = 2560x550
  scale = 1
  transform = 0
}

monitorv2 {
  output = $monitor_03
  mode =  1366x768@60
  position = -1366x150
  scale = 1
  transform = 0
}


# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░
input {
  kb_layout = us
  # kb_variant = altgr-intl
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  accel_profile = flat
  tablet{
    output = current
  }
}

binds{
  movefocus_cycles_fullscreen = true
}


# █▀▀ █▀▀ █▄░█ █▀▀ █▀█ ▄▀█ █░░
# █▄█ ██▄ █░▀█ ██▄ █▀▄ █▀█ █▄▄
general {
  allow_tearing = true
  gaps_in = 0
  gaps_out = 0
  border_size = 3
  col.active_border = rgba(b4befeff) rgba(cba6f7ff)
  col.inactive_border = rgba(595959aa)
  layout = scrolling
  resize_on_border = true
  snap{
    enabled = true
    window_gap = 30
    monitor_gap = 30
  }
}


# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
  on_focus_under_fullscreen = 1
  exit_window_retains_fullscreen = true
}


# █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

decoration {
  rounding = 8
  active_opacity = 1.0
  inactive_opacity = 1.0

  blur {
    enabled = true
    size = 3
    passes = 3
    new_optimizations = true
  }

  shadow {

  }

}


# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
animations {
  enabled = true
  # █▄▄ █▀▀ ▀█ █ █▀▀ █▀█   █▀▀ █░█ █▀█ █░█ █▀▀
  # █▄█ ██▄ █▄ █ ██▄ █▀▄   █▄▄ █▄█ █▀▄ ▀▄▀ ██▄
  bezier = overshot, 0.05, 0.9, 0.1, 1.05
  bezier = smoothOut, 0.36, 0, 0.66, -0.56
  bezier = smoothIn, 0.25, 1, 0.5, 1
  bezier = linear, 0, 0, 1, 1

  animation = windows, 1, 5, overshot, slide
  animation = windowsOut, 1, 4, smoothOut, slide
  animation = windowsMove, 1, 4, default
  animation = border, 1, 10, default
  # animation = borderangle, 1, 40, linear, loop
  animation = fade, 1, 10, smoothIn
  animation = fadeDim, 1, 10, smoothIn
  animation = workspaces, 1, 6, default
}


# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█
dwindle {
  # pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = true # you probably want this
}

scrolling {
  column_width = 0.9
  focus_fit_method = 0
}

master {
}

source=~/.config/hypr/window_rules.conf
source=~/.config/hypr/worspace_rules.conf
#Binds
source=~/.config/hypr/binds.conf
