workspace = 1, monitor:$monitor_01
workspace = 2, monitor:$monitor_01
workspace = 3, monitor:$monitor_01
workspace = 4, monitor:$monitor_01
workspace = 5, monitor:$monitor_01
workspace = 11, monitor:$monitor_01
workspace = 12, monitor:$monitor_01
workspace = 13, monitor:$monitor_01
workspace = 14, monitor:$monitor_01
workspace = 15, monitor:$monitor_01

workspace = 6, monitor:$monitor_02
workspace = 7, monitor:$monitor_02
workspace = 8, monitor:$monitor_02
workspace = 16, monitor:$monitor_02
workspace = 17, monitor:$monitor_02
workspace = 18, monitor:$monitor_02

workspace = 9, monitor:$monitor_03
workspace = 10, monitor:$monitor_03
workspace = 19, monitor:$monitor_03
workspace = 20, monitor:$monitor_03


workspace = 3, fullscren: true
