#!/bin/bash

monitorId=1
monitorInfo=$(hyprctl monitors | awk '/^Monitor [^ ]+ \(ID '$monitorId'\):/,/^$/' )
# echo $monitorInfo


# Use awk to extract the "transform" parameter and remove any non-numeric characters
transform=$(echo "$monitorInfo" | awk -F 'transform:' '{print $2}' | tr -cd '[:digit:]')

# Print the extracted "transform" parameter
echo $transform


if [ $transform -eq 0 ]
then
  hyprctl keyword monitor HDMI-A-1, 1920x1080, 2560x0, .9, transform, 3
else
  hyprctl keyword monitor HDMI-A-1, 1920x1080, 2560x0, .9
fi
