#!/bin/bash
# Use vim keys in tab complete menu:

function zvm_after_init() {
  bindkey -M menuselect 'h' vi-backward-char
  bindkey -M menuselect 'k' vi-up-line-or-history
  bindkey -M menuselect 'l' vi-forward-char
  bindkey -M menuselect 'j' vi-down-line-or-history
  bindkey -v '^?' backward-delete-char
  bindkey -M viins '\es' self-insert
  bindkey -M viins '\eS' self-insert
}


