# Apps
# Any monitor

windowrule {
  name = pie Widget
  match:class = krita
  match:title = ^(Pie Widget — Krita)$

  no_anim = true
  no_blur = true
  no_shadow = true
  border_size = 0
}

windowrule {
  name = krita_pie_menu
  match:class = krita
  match:title = ^(Rotation Widget — Krita)$

  no_anim = true
  no_blur = true
  no_shadow = true
  border_size = 0
}
windowrule {
  name = no_stream
  match:class = org.mozilla.Thunderbird
  no_screen_share = true
}
windowrule {
  name = float_blender
  match:class = blender
  match:float = true
  size = (window_w*6) (window_h*5)
  center = true
}
# # windowrule = float, class:blender title:Blender File View
# windowrule = float,class:^(blueberry.py)$,
# windowrule = center,class:^(blueberry.py)$,
# windowrule = size 700 800,class:^(blueberry.py)$
#
#
# # Monitor 01
# windowrule = workspace 3, class:^(blender|Godot|krita|inochi-creator)$
# windowrule = workspace 3, class:^gimp.*$
# # windowrule = fullscreen, intialClass:blender, initialTitle:Blender
#
# # windowrule = suppressevent maximize, class:^(blender)$
#
# # windowrule = fullscreenstate 0 2, class:^(blender)$
# # windowrule = fullscreen, class:^(blender)$
#
windowrule {
  name = games
  match:class = ^(steam_app_)(.*)$
  workspace = 13
}

# windowrule = workspace 13, class:gamescope
#
# windowrule = workspace 5, class:(discord)$
#
# windowrule = workspace 5, class:^(org.telegram.desktop)$


windowrule {
  name = telegram_media
  match:class = org.telegram.desktop
  match:title = メディアビューア
  fullscreen_state = 0 0
  float = true
  # opaque = false
}
# # windowrule = fullscreenstate 0 0, class:org.telegram.desktop, title:メディアビューア
# windowrule = float, class:org.telegram.desktop, title:メディアビューア
# windowrule = opaque, class:org.telegram.desktop, title:メディアビューア
#
# #fixit: this doesn't work becuase this is a static rule
# # i'm thinking Floatof maybe changing it to a scripts so when i open this with a shortcut it moves them
# # to the correct monitor
# windowrule = workspace 13, title:btop, tintialTitle:kitty
#Float

windowrule {
  name = pureref
  match:title = ^(PureRef)$
  float = true
}
# # windowrule = stayfocused, title:PureRef
# windowrule = float, title:^(PureRef)$
# # windowrule = fullscreenstate 0 2, title:^(PureRef)$
#
#
# # Monitor 02
windowrule {
  name = game_launcher
  match:class = ^(steam|com.usebottles.bottles|heroic)
  workspace = 16
}


# # windowrule = workspace 6, title:3D Viewport
# # windowrule = noinitialfocus, title:3D Viewport
# # windowrule = fullscreen, title:3D Viewport
# windowrule = workspace 9, title:(WhatsApp)$
# windowrule = workspace 8, class:(obs)$, title:^.* - Profile:.*$
# windowrule = fullscreen, class:(obs)$, title:^.* - Profile:.*$
#
# windowrule = fullscreen, class:^(veadotube-mini)$
# windowrule = nofocus, class:^(veadotube-mini)$
# windowrule = workspace 18, class:^veadotube-mini$
#
# windowrule = renderunfocused, class:^(PNGTube-Remix)$
# windowrule = tile, class:^(PNGTube-Remix)$
#
# windowrule = workspace 8, class:(com.chatterino.chatterino)$
# windowrule = maxsize 300 1000, class:(com.chatterino.chatterino)$


#
# Monitor 03
windowrule {
  name = pomodorolm
  match:class = ^(pomodorolm)$
  workspace = 19
  float = true
  move = (monitor_w*0.73) (monitor_h*0.05)
  xray = true
}

windowrule {
  name = spotify
  match:class = ^(spotify)$
  no_initial_focus = true
  workspace = 19
  fullscreen = true
}

windowrule {
  name = phone_audio_to_pc
  match:class = scrcpy
	match:title = 2201117SG
  no_initial_focus = true
  workspace = 19
}

# windowrule = workspace 20, class:^(org.qbittorrent.qBittorrent)$
